
---
- name: Create direct rule
  shell:
    cmd: |
      set -o errexit ;
      CHANGED=1 ;
      for opt in '' '--permanent'; do
        if ! firewall-cmd $opt --direct --query-rule {{ firewalld_direct_enabled_rule }} ; then
          firewall-cmd $opt --direct --add-rule {{ firewalld_direct_enabled_rule }} ;
          CHANGED=0 ;
        fi
      done
      if [ $CHANGED -eq 0 ] ; then
        echo "changed";
      else
        echo "skipped";
      fi
    executable: /bin/bash
  register: command_result
  changed_when: command_result.stdout_lines|length > 0 and command_result.stdout_lines[-1] == 'changed'
