
---
- name: Unset zone masquerade
  firewalld:
    masquerade: "{{ firewalld_zone.disabled.masquerade }}"
    permanent: true
    immediate: true
    state: disabled
    zone: "{{ firewalld_zone.name }}"
  when: (firewalld_zone.disabled.masquerade is defined)

- name: Unset zone icmp_blocks
  firewalld:
    icmp_block: "{{ item }}"
    permanent: true
    immediate: true
    state: disabled
    zone: "{{ firewalld_zone.name }}"
  loop: "{{ firewalld_zone.disabled.icmp_blocks|default([]) }}"

- name: Unset zone icmp_block_inversion
  firewalld:
    icmp_block_inversion: "{{ firewalld_zone.disabled.icmp_block_inversion }}"
    permanent: true
    immediate: true
    state: disabled
    zone: "{{ firewalld_zone.name }}"
  when: (firewalld_zone.disabled.icmp_block_inversion is defined)

- name: Remove zone sources
  firewalld:
    source: "{{ item }}"
    permanent: true
    immediate: true
    state: disabled
    zone: "{{ firewalld_zone.name }}"
  loop: "{{ firewalld_zone.disabled.sources|default([]) }}"

- name: Remove zone interfaces
  firewalld:
    interface: "{{ item }}"
    permanent: true
    immediate: true
    state: disabled
    zone: "{{ firewalld_zone.name }}"
  loop: "{{ firewalld_zone.disabled.interfaces|default([]) }}"

- name: Remove zone services
  firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: disabled
    zone: "{{ firewalld_zone.name }}"
  loop: "{{ firewalld_zone.disabled.services|default([]) }}"

- name: Remove zone port
  firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: true
    state: disabled
    zone: "{{ firewalld_zone.name }}"
  loop: "{{ firewalld_zone.disabled.ports|default([]) }}"

- name: Remove zone port forward
  firewalld:
    port_forward: "{{ item }}"
    permanent: true
    immediate: true
    state: disabled
    zone: "{{ firewalld_zone.name }}"
  loop: "{{ firewalld_zone.disabled.port_forwards|default([]) }}"

- name: Remove zone rich rule
  firewalld:
    rich_rule: "{{ item }}"
    permanent: true
    immediate: true
    state: disabled
    zone: "{{ firewalld_zone.name }}"
  loop: "{{ firewalld_zone.disabled.rich_rules|default([]) }}"

- name: Remove zone protocol
  shell:
    cmd: |
      set -o errexit ;
      CHANGED=1 ;
      for opt in '' '--permanent'; do
        if firewall-cmd $opt --zone="{{ firewalld_zone.name }}" --query-protocol="{{ item }}" ; then
          firewall-cmd $opt --zone="{{ firewalld_zone.name }}" --remove-protocol="{{ item }}" ;
          CHANGED=0 ;
        fi
      done
      if [ $CHANGED -eq 0 ] ; then
        echo "changed";
      else
        echo "skipped";
      fi
    executable: /bin/bash
  register: command_result
  changed_when: command_result.stdout_lines|length > 0 and command_result.stdout_lines[-1] == 'changed'
  loop: "{{ firewalld_zone.disabled.protocols|default([]) }}"
