
---
- name: Remove direct chain
  shell:
    cmd: |
      set -o errexit ;
      CHANGED=1 ;
      for opt in '' '--permanent'; do
        if firewall-cmd $opt --direct --query-chain {{ firewalld_direct_disabled_chain }} ; then
          firewall-cmd $opt --direct --remove-chain {{ firewalld_direct_disabled_chain }} ;
          CHANGED=0 ;
        fi
      done
      if [ $CHANGED -eq 0 ] ; then
        echo "changed";
      else
        echo "skipped";
      fi
    executable: /bin/bash
  register: command_result
  changed_when: command_result.stdout_lines|length > 0 and command_result.stdout_lines[-1] == 'changed'
